[colors.primary]
background = "#1b1e25"
foreground = "#c6c6c8"

[colors.cursor]
text = "#1b1e25"
cursor = "#c6c6c8"

[colors.vi_mode_cursor]
text = "#1b1e25"
cursor = "#c6c6c8"

[colors.search.matches]
foreground = "#1b1e25"
background = "#c6c6c8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#626878"
background = "#c6c6c8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#1b1e25"
red = "#738C90"
green = "#7DA2A4"
yellow = "#96A5A8"
blue = "#8FBBBA"
magenta = "#95C0BF"
cyan = "#A8BFC0"
white = "#c6c6c8"

[colors.bright]
black = "#626878"
red = "#738C90"
green = "#7DA2A4"
yellow = "#96A5A8"
blue = "#8FBBBA"
magenta = "#95C0BF"
cyan = "#A8BFC0"
white = "#c6c6c8"

[colors.dim]
black = "#c6c6c8"
red = "#738C90"
green = "#95C0BF"
yellow = "#96A5A8"
blue = "#8FBBBA"
magenta = "#7DA2A4"
cyan = "#A8BFC0"
white = "#626878"

