[colors]
background = '#1b1e258e'
black = '#1b1e25'
blue = '#D08971'
cursor = '#c6c6c8'
cyan = '#5B769A'
foreground = '#c6c6c8'
green = '#967789'
magenta = '#5E81AB'
red = '#6C8BAD'
tabs = '#c6c6c8'
tabs-active = '#7CA2C2'
white = '#c6c6c8'
yellow = '#c6c6c8'
dim-black = '#1b1e258e'
dim-blue = '#D089718e'
dim-cyan = '#5B769A8e'
dim-foreground = '#c6c6c88e'
dim-green = '#9677898e'
dim-magenta = '#5E81AB8e'
dim-red = '#6C8BAD8e'
dim-white = '#7CA2C28e'
dim-yellow = '#c6c6c88e'
light-black = '#D08971'
light-blue = '#5B769A'
light-cyan = '#967789'
light-foreground = '#5E81AB'
light-green = '#6C8BAD'
light-magenta = '#7CA2C2'
light-red = '#c6c6c8'
light-white = '#D08971'
light-yellow = '#5B769A'
