[colors]
background = '#191c248e'
black = '#191c24'
blue = '#3E5A81'
cursor = '#c5c6c8'
cyan = '#5B7192'
foreground = '#c5c6c8'
green = '#6C8DAE'
magenta = '#7AABC4'
red = '#B08482'
tabs = '#c5c6c8'
tabs-active = '#9B96AC'
white = '#c5c6c8'
yellow = '#c5c6c8'
dim-black = '#191c248e'
dim-blue = '#3E5A818e'
dim-cyan = '#5B71928e'
dim-foreground = '#c5c6c88e'
dim-green = '#6C8DAE8e'
dim-magenta = '#7AABC48e'
dim-red = '#B084828e'
dim-white = '#9B96AC8e'
dim-yellow = '#c5c6c88e'
light-black = '#3E5A81'
light-blue = '#5B7192'
light-cyan = '#6C8DAE'
light-foreground = '#7AABC4'
light-green = '#B08482'
light-magenta = '#9B96AC'
light-red = '#c5c6c8'
light-white = '#3E5A81'
light-yellow = '#5B7192'
