[colors.primary]
background = "#191c24"
foreground = "#c5c6c8"

[colors.cursor]
text = "#191c24"
cursor = "#c5c6c8"

[colors.vi_mode_cursor]
text = "#191c24"
cursor = "#c5c6c8"

[colors.search.matches]
foreground = "#191c24"
background = "#c5c6c8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#616777"
background = "#c5c6c8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#191c24"
red = "#3E5A81"
green = "#5B7192"
yellow = "#6C8DAE"
blue = "#7AABC4"
magenta = "#B08482"
cyan = "#9B96AC"
white = "#c5c6c8"

[colors.bright]
black = "#616777"
red = "#3E5A81"
green = "#5B7192"
yellow = "#6C8DAE"
blue = "#7AABC4"
magenta = "#B08482"
cyan = "#9B96AC"
white = "#c5c6c8"

[colors.dim]
black = "#c5c6c8"
red = "#3E5A81"
green = "#B08482"
yellow = "#6C8DAE"
blue = "#7AABC4"
magenta = "#5B7192"
cyan = "#9B96AC"
white = "#616777"

