[colors]
background = '#181b228e'
black = '#181b22'
blue = '#68787E'
cursor = '#c5c6c7'
cyan = '#537E82'
foreground = '#c5c6c7'
green = '#767D83'
magenta = '#7D8288'
red = '#85898E'
tabs = '#c5c6c7'
tabs-active = '#9A9EA2'
white = '#c5c6c7'
yellow = '#c5c6c7'
dim-black = '#181b228e'
dim-blue = '#68787E8e'
dim-cyan = '#537E828e'
dim-foreground = '#c5c6c78e'
dim-green = '#767D838e'
dim-magenta = '#7D82888e'
dim-red = '#85898E8e'
dim-white = '#9A9EA28e'
dim-yellow = '#c5c6c78e'
light-black = '#68787E'
light-blue = '#537E82'
light-cyan = '#767D83'
light-foreground = '#7D8288'
light-green = '#85898E'
light-magenta = '#9A9EA2'
light-red = '#c5c6c7'
light-white = '#68787E'
light-yellow = '#537E82'
