[colors]
background = '#1b1e258e'
black = '#1b1e25'
blue = '#658185'
cursor = '#c6c6c8'
cyan = '#688589'
foreground = '#c6c6c8'
green = '#6E8E91'
magenta = '#6F8E91'
red = '#7B9FA0'
tabs = '#c6c6c8'
tabs-active = '#7DA2A4'
white = '#c6c6c8'
yellow = '#c6c6c8'
dim-black = '#1b1e258e'
dim-blue = '#6581858e'
dim-cyan = '#6885898e'
dim-foreground = '#c6c6c88e'
dim-green = '#6E8E918e'
dim-magenta = '#6F8E918e'
dim-red = '#7B9FA08e'
dim-white = '#7DA2A48e'
dim-yellow = '#c6c6c88e'
light-black = '#658185'
light-blue = '#688589'
light-cyan = '#6E8E91'
light-foreground = '#6F8E91'
light-green = '#7B9FA0'
light-magenta = '#7DA2A4'
light-red = '#c6c6c8'
light-white = '#658185'
light-yellow = '#688589'
