[colors.primary]
background = "#12171f"
foreground = "#c3c5c7"

[colors.cursor]
text = "#12171f"
cursor = "#c3c5c7"

[colors.vi_mode_cursor]
text = "#12171f"
cursor = "#c3c5c7"

[colors.search.matches]
foreground = "#12171f"
background = "#c3c5c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5e6772"
background = "#c3c5c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#12171f"
red = "#6E91AF"
green = "#7496AC"
yellow = "#7CA8C2"
blue = "#8DA2B4"
magenta = "#9AB5C7"
cyan = "#B4C7D5"
white = "#c3c5c7"

[colors.bright]
black = "#5e6772"
red = "#6E91AF"
green = "#7496AC"
yellow = "#7CA8C2"
blue = "#8DA2B4"
magenta = "#9AB5C7"
cyan = "#B4C7D5"
white = "#c3c5c7"

[colors.dim]
black = "#c3c5c7"
red = "#6E91AF"
green = "#9AB5C7"
yellow = "#7CA8C2"
blue = "#8DA2B4"
magenta = "#7496AC"
cyan = "#B4C7D5"
white = "#5e6772"

