[colors]
background = '#1b1e258e'
black = '#1b1e25'
blue = '#738C90'
cursor = '#c6c6c8'
cyan = '#7DA2A4'
foreground = '#c6c6c8'
green = '#96A5A8'
magenta = '#8FBBBA'
red = '#95C0BF'
tabs = '#c6c6c8'
tabs-active = '#A8BFC0'
white = '#c6c6c8'
yellow = '#c6c6c8'
dim-black = '#1b1e258e'
dim-blue = '#738C908e'
dim-cyan = '#7DA2A48e'
dim-foreground = '#c6c6c88e'
dim-green = '#96A5A88e'
dim-magenta = '#8FBBBA8e'
dim-red = '#95C0BF8e'
dim-white = '#A8BFC08e'
dim-yellow = '#c6c6c88e'
light-black = '#738C90'
light-blue = '#7DA2A4'
light-cyan = '#96A5A8'
light-foreground = '#8FBBBA'
light-green = '#95C0BF'
light-magenta = '#A8BFC0'
light-red = '#c6c6c8'
light-white = '#738C90'
light-yellow = '#7DA2A4'
