[colors.primary]
background = "#181b22"
foreground = "#c5c6c7"

[colors.cursor]
text = "#181b22"
cursor = "#c5c6c7"

[colors.vi_mode_cursor]
text = "#181b22"
cursor = "#c5c6c7"

[colors.search.matches]
foreground = "#181b22"
background = "#c5c6c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#606676"
background = "#c5c6c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#181b22"
red = "#68787E"
green = "#537E82"
yellow = "#767D83"
blue = "#7D8288"
magenta = "#85898E"
cyan = "#9A9EA2"
white = "#c5c6c7"

[colors.bright]
black = "#606676"
red = "#68787E"
green = "#537E82"
yellow = "#767D83"
blue = "#7D8288"
magenta = "#85898E"
cyan = "#9A9EA2"
white = "#c5c6c7"

[colors.dim]
black = "#c5c6c7"
red = "#68787E"
green = "#85898E"
yellow = "#767D83"
blue = "#7D8288"
magenta = "#537E82"
cyan = "#9A9EA2"
white = "#606676"

