[colors.primary]
background = "#1b1e25"
foreground = "#c6c6c8"

[colors.cursor]
text = "#1b1e25"
cursor = "#c6c6c8"

[colors.vi_mode_cursor]
text = "#1b1e25"
cursor = "#c6c6c8"

[colors.search.matches]
foreground = "#1b1e25"
background = "#c6c6c8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#626878"
background = "#c6c6c8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#1b1e25"
red = "#658185"
green = "#688589"
yellow = "#6E8E91"
blue = "#6F8E91"
magenta = "#7B9FA0"
cyan = "#7DA2A4"
white = "#c6c6c8"

[colors.bright]
black = "#626878"
red = "#658185"
green = "#688589"
yellow = "#6E8E91"
blue = "#6F8E91"
magenta = "#7B9FA0"
cyan = "#7DA2A4"
white = "#c6c6c8"

[colors.dim]
black = "#c6c6c8"
red = "#658185"
green = "#7B9FA0"
yellow = "#6E8E91"
blue = "#6F8E91"
magenta = "#688589"
cyan = "#7DA2A4"
white = "#626878"

