[colors]
background = '#12171f8e'
black = '#12171f'
blue = '#6E91AF'
cursor = '#c3c5c7'
cyan = '#7496AC'
foreground = '#c3c5c7'
green = '#7CA8C2'
magenta = '#8DA2B4'
red = '#9AB5C7'
tabs = '#c3c5c7'
tabs-active = '#B4C7D5'
white = '#c3c5c7'
yellow = '#c3c5c7'
dim-black = '#12171f8e'
dim-blue = '#6E91AF8e'
dim-cyan = '#7496AC8e'
dim-foreground = '#c3c5c78e'
dim-green = '#7CA8C28e'
dim-magenta = '#8DA2B48e'
dim-red = '#9AB5C78e'
dim-white = '#B4C7D58e'
dim-yellow = '#c3c5c78e'
light-black = '#6E91AF'
light-blue = '#7496AC'
light-cyan = '#7CA8C2'
light-foreground = '#8DA2B4'
light-green = '#9AB5C7'
light-magenta = '#B4C7D5'
light-red = '#c3c5c7'
light-white = '#6E91AF'
light-yellow = '#7496AC'
